sonar.projectKey=antholim_SOEN345-PROJECT
sonar.organization=antholim
sonar.projectName=SOEN345-PROJECT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
