-- H2-compatible schema for integration/system tests.
-- Enum columns use VARCHAR because VarcharEnumTypeContributor remaps NAMED_ENUM -> VARCHAR for H2.

CREATE TABLE IF NOT EXISTS users (
    user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(50)  NOT NULL,
    last_name     VARCHAR(50)  NOT NULL,
    email         VARCHAR(100) UNIQUE,
    phone_number  VARCHAR(20)  UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT chk_users_contact CHECK (email IS NOT NULL OR phone_number IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS venues (
    venue_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name  VARCHAR(100) NOT NULL,
    address     VARCHAR(255) NOT NULL,
    city        VARCHAR(100) NOT NULL,
    capacity    INTEGER      NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    category_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    event_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(100)   NOT NULL,
    description       TEXT,
    event_date        TIMESTAMP      NOT NULL,
    available_tickets INTEGER        NOT NULL,
    price             DECIMAL(10, 2) NOT NULL,
    status            VARCHAR(20)    NOT NULL,
    venue_id          INTEGER        NOT NULL REFERENCES venues(venue_id),
    category_id       INTEGER        NOT NULL REFERENCES categories(category_id),
    created_at        TIMESTAMP,
    created_by        INTEGER        NOT NULL
);

CREATE TABLE IF NOT EXISTS reservations (
    reservation_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           INTEGER        NOT NULL REFERENCES users(user_id),
    event_id          INTEGER        NOT NULL REFERENCES events(event_id),
    number_of_tickets INTEGER        NOT NULL,
    reservation_date  TIMESTAMP,
    status            VARCHAR(20)    NOT NULL,
    total_price       DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS confirmations (
    confirmation_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id       INTEGER     NOT NULL REFERENCES reservations(reservation_id),
    confirmation_type    VARCHAR(20) NOT NULL,
    sent_at              TIMESTAMP   NOT NULL,
    confirmation_message TEXT
);
