do $$
begin
    if not exists (select 1 from pg_type where typname = 'user_role') then
        create type user_role as enum ('CUSTOMER', 'ADMIN');
    end if;

    if not exists (select 1 from pg_type where typname = 'event_status') then
        create type event_status as enum ('ACTIVE', 'CANCELLED');
    end if;

    if not exists (select 1 from pg_type where typname = 'reservation_status') then
        create type reservation_status as enum ('CONFIRMED', 'CANCELLED');
    end if;

    if not exists (select 1 from pg_type where typname = 'confirmation_type') then
        create type confirmation_type as enum ('EMAIL', 'SMS');
    end if;
end $$;

create table if not exists users (
    user_id integer generated by default as identity primary key,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(100) not null unique,
    phone_number varchar(20) unique,
    password_hash varchar(255) not null,
    role user_role not null default 'CUSTOMER',
    created_at timestamp default current_timestamp
);

create table if not exists venues (
    venue_id integer generated by default as identity primary key,
    venue_name varchar(100) not null,
    address varchar(255) not null,
    city varchar(100) not null,
    capacity integer not null,
    constraint chk_venues_capacity check (capacity >= 0)
);

create table if not exists categories (
    category_id integer generated by default as identity primary key,
    category_name varchar(50) not null unique
);

create table if not exists events (
    event_id integer generated by default as identity primary key,
    title varchar(100) not null,
    description text,
    event_date timestamp not null,
    available_tickets integer not null,
    price numeric(10, 2) not null,
    status event_status not null default 'ACTIVE',
    venue_id integer not null references venues (venue_id),
    category_id integer not null references categories (category_id),
    created_by integer not null references users (user_id),
    created_at timestamp default current_timestamp,
    constraint chk_events_available_tickets check (available_tickets >= 0),
    constraint chk_events_price check (price >= 0)
);

create table if not exists reservations (
    reservation_id integer generated by default as identity primary key,
    user_id integer not null references users (user_id),
    event_id integer not null references events (event_id),
    number_of_tickets integer not null,
    reservation_date timestamp default current_timestamp,
    status reservation_status not null default 'CONFIRMED',
    total_price numeric(10, 2) not null,
    constraint chk_reservations_number_of_tickets check (number_of_tickets > 0),
    constraint chk_reservations_total_price check (total_price >= 0)
);

create table if not exists confirmations (
    confirmation_id integer generated by default as identity primary key,
    reservation_id integer not null unique references reservations (reservation_id),
    confirmation_type confirmation_type not null,
    sent_at timestamp default current_timestamp,
    confirmation_message text
);
